paths:
  usr_name: hailuo          # modify this
  data_dir: /cluster/courses/cil/monocular_depth/data
  results_dir: results
  predictions_dir: predictions

experiment:
  # model_name: midas_semantics  # Name to use when saving the model
  model_name: midas_small_lb  # Name to use when saving the model
  wandb_disable: False

training:
  n_epoch: 10
  batch_size: 4
  early_stopping:
    patience: 2
    min_delta: 1e-4

model:
  model_type: MiDaS_small
  # dinov2_type: dinov2_vits14
  # dinov2_type: dinov2_vitb14
  dinov2_type: null
  network:
    use_lb: true
  
opt:
  evaluate_best_model: false