paths:
  usr_name: hailuo          # modify this
  data_dir: /cluster/courses/cil/monocular_depth/data
  results_dir: results
  predictions_dir: predictions

experiment:
  model_name: midas_small_skip_nolb  # Name to use when saving the model
  wandb_disable: False

training:
  n_epoch: 10
  batch_size: 4
  resume_training: 
    resume: False
    resume_from_epoch: 6
    run_id: 7iju0bam
  early_stopping:
    patience: 2
    min_delta: 1e-4

model:
  model_type: MiDaS_small
  # dinov2_type: dinov2_vits14
  # dinov2_type: dinov2_vitb14
  dinov2_type: null
  use_skip: True
  network:
    use_lb: false
  use_lb: false  # For visualize.py
  loss_function:
    # grad_loss_alpha: 0.2  # Weight for gradient loss
    grad_loss_alpha: 0  # Weight for gradient loss
    # edge_loss_beta: 0.5  # Weight for edge-aware loss
    edge_loss_beta: 0  # Weight for edge-aware loss

opt:
  evaluate_best_model: false