paths:
  usr_name: hailuo          # modify this
  data_dir: /cluster/courses/cil/monocular_depth/data
  results_dir: results
  predictions_dir: predictions

experiment:
  model_name: midas_small_nolb_w_grad_loss  # Name to use when saving the model
  wandb_disable: False

training:
  n_epoch: 10
  batch_size: 4
  resume_training: 
    resume: False
    resume_from_epoch: 6
    run_id: 7iju0bam
  early_stopping:
    patience: 2
    min_delta: 1e-4

model:
  model_type: MiDaS_small
  # dinov2_type: dinov2_vits14
  # dinov2_type: dinov2_vitb14
  dinov2_type: null
  network:
    use_lb: false
  loss_function:
    grad_loss_alpha: 0.5  # Weight for gradient loss

opt:
  evaluate_best_model: false