paths:
  usr_name: hrluo
  data_dir: /home/hrluo/monocular-depth-estimation-cil/data
  results_dir: results
  predictions_dir: predictions
  best_model_path: results/best_model.pth

training:
  n_epoch: 100
  batch_size: 4
  resume_training: false  # Set to true to resume from checkpoint
  checkpoint_path: "checkpoint_epoch_X.pth"  # Replace X with the epoch number to resume from

model:
  model_type: DPT_Hybrid
  backbone: vitb_rn50_384
  network:
    n_layer: 0      # not used
  dinov2_type: dinov2_vitb14
  
opt:
  evaluate_best_model: false
