paths:
  usr_name: lingxi          # modify this
  data_dir: /cluster/courses/cil/monocular_depth/data
  results_dir: results
  predictions_dir: predictions
  best_model_path: results/best_model.pth

training:
  n_epoch: 10
  batch_size: 4

model:
  model_type: MiDaS_small
  network:
    use_lb: true
    use_dgr: true
  
opt:
  evaluate_best_model: false


exp_name: midas_small_lb
wandb_disable: True