paths:
  usr_name: hailuo          # modify this
  data_dir: /cluster/courses/cil/monocular_depth/data
  results_dir: results
  predictions_dir: predictions
  best_model_path: results/best_model.pth

training:
  n_epoch: 10
  batch_size: 4

model:
  model_type: MiDaS_small
  dinov2_type: dinov2_vits14
  # dinov2_type: dinov2_vitb14
  # dinov2_type: null
  network:
    use_lb: true
  
opt:
  evaluate_best_model: false


exp_dir: midas_small_lb
wandb_disable: False